### ISSUE TITLE
Cyclic Dependency

### ISSUE THREAD

**Issue by gglerum** [Emilvdijk/quizwebgame#8]
Je hebt een cyclic dependency via meerdere lagen op je `UserAlreadyExistsConstraint`. Als je in de file/project explorer rechts klikt op de module en kiest voor 'analyze -> analyze cyclic dependencies' dan zie je dat op verschillende manieren classes/annotaties naar elkaar verwijzen. 

In de regel wil je dat dependencies alleen maar één kant op wijzen. Maar ik ben onvoldoende thuis in validatie en constraints om te oordelen of dit wel of niet goed in elkaar zit.

**Comment by Emilvdijk** [comment]
na een 2e kijk naar guides en voorbeelden snap ik het nu. wat ik niet helemaal snap is de interface van Intellij over analyze, misschien kun je daar nog wat van laten zien
